### ISSUE TITLE
Huge security downside

### ISSUE THREAD

**Issue by 0x090909** [avilum/llama-saas#2]
Project is great, but the fact that you interact with lama via `exec` is not good, since easily the machine hosting the model could get compromised, via remote code execution.

I would suggest to implement the C bindings in Go, and call the model with the native APIs.

**Comment by avilum** [comment]
Hey, 
The idea was to spawn a new process for every prompt (larger PCs can handle that).
The tensor library used by llama.cpp has no thread safety nor C api.

I agree in general that the exec API is too privileged and unsafe by design, but we can sanitize and input easily before passing it to the Exec command.

You are welcome to try adding C wrappers and replace this, I cannot work on it at the moment, - and I rather work on interactive chat API (interactive mode) and other cool features with more impact.
